import type { ServicePage } from "@/types";

const customLmsFaqs: ServicePage["faqs"] = [
  { question: "How much does custom LMS development cost?", answer: "It depends on the hard parts: how many distinct learner flows, how much data you're migrating, the integrations, and the reporting you actually need. We scope a narrow first release with a clear second step and share the assumptions in the open, then quote the specific piece of work. A number without those details is a delayed surprise." },
  { question: "How long until the first release?", answer: "Most focused platforms are usable in 8 to 12 weeks. We work in weekly slices, so you're clicking through the real thing early instead of waiting months for a slide deck." },
  { question: "Do we own the code?", answer: "Yes. At handover you get the application code, deployment docs, and the infrastructure access we agreed in the plan. Ongoing support is available, never required." },
  { question: "Can it work with the systems we already run?", answer: "Where the API or standard supports it, yes. We confirm identity, payments, content packages, and reporting during technical discovery rather than assuming an integration is simple." },
];

const corporateFaqs: ServicePage["faqs"] = [
  { question: "How much does a corporate training platform cost?", answer: "The moving parts are SSO, HRIS connections, compliance evidence, partner training, and migrating historic records. We scope the reporting questions before quoting, because that is where vague requirements get expensive. Every estimate we share is tied to a specific scope, not a marketing range." },
  { question: "How long does it take to launch?", answer: "Around 8 to 12 weeks for the core, in weekly builds. Identity and role data get proven first, because a polished dashboard with the wrong access model is expensive wallpaper." },
  { question: "Will it connect to our SSO and HR systems?", answer: "That's usually the point. We confirm the identity provider, the systems of record, and the exact sign-in flow during discovery, then place people into the right roles automatically instead of asking a manager to update a group by hand." },
  { question: "How do you handle compliance evidence and old records?", answer: "We record attempts, acknowledgement, expiry, certificates, and the version of the material a learner saw, so an audit is a report rather than a scramble. Historic records either migrate or move to a retained archive with a clear audit path, decided before cutover." },
];

const creatorFaqs: ServicePage["faqs"] = [
  { question: "How much does a custom course platform cost?", answer: "The cost moves with the shape of the offer: custom checkout logic, memberships, team purchasing, a catalogue migration, or a built-in community all push it up. We scope around the offer that makes money now, not the hypothetical one three years out, and quote against that specific plan." },
  { question: "How soon can I start selling on it?", answer: "Usually 8 to 12 weeks, built in weekly slices. You can start selling once the purchase-and-delivery path is proven, before every feature is polished." },
  { question: "Do I keep my payment processor and revenue?", answer: "Yes. The platform connects to the payment provider you choose and takes no cut on top of the processor fee. Owning the checkout is usually the whole reason to build." },
  { question: "Can you migrate my existing courses and students?", answer: "We export what your current tool allows, courses, media, and customer records, rebuild the flows that matter, and test buying, access, and refunds with real-looking data before anyone switches." },
];

const schoolFaqs: ServicePage["faqs"] = [
  { question: "How much does a school student portal cost?", answer: "SIS integration, the number of roles, parent access, gradebook needs, and legacy data migration move the number the most. We usually start with the student service causing the most friction, then expand from a stable base, and quote against that specific first release rather than a generic range." },
  { question: "How long does it take to launch?", answer: "About 8 to 12 weeks for a focused first release. The high-volume paths, sign-in, timetable, assignments, get built and validated first." },
  { question: "Who owns and protects the student data?", answer: "Your institution controls the environment and the data-access model. We design permissions, audit needs, retention, and incident responsibilities with you, and document them before launch rather than after." },
  { question: "Do we have to replace our SIS and LMS?", answer: "No, and replacing everything is often the riskiest first move. The SIS can stay the source of truth for enrolment and the LMS can keep course content, while the portal gives students, parents, and staff one front door through tested integrations." },
];

export const services: ServicePage[] = [
  {
    slug: "custom-lms-development",
    title: "Custom LMS Development",
    metaTitle: "Custom LMS Development for Learning Products | Rizon",
    metaDescription: "Custom LMS development for teams that have outgrown off-the-shelf software and need a learning platform built around their learners, data, and business.",
    h1: "Custom LMS development for the way your learning business actually works.",
    heroSub: "For founders and operations leads who have outgrown their LMS, we build an owned platform around the learner journey, commercial model, and systems you already run.",
    targetKeyword: "custom LMS development",
    whoWeWorkWith: [
      { audience: "Education businesses", description: "Companies whose product is the learning platform: cohort programmes, professional courses, certification bodies. The LMS decides how the offer can be sold and delivered, which is why it stops being someone else's job to fix." },
      { audience: "Training companies", description: "B2B and B2C providers running blended or on-demand programmes with enterprise buyers, seat allocation, cohort scheduling, and structured reporting back to end clients." },
      { audience: "Schools, universities, and multi-tenant academies", description: "Institutions and networks whose learner base needs role-specific access, SIS or SSO integration, and reporting that a generic LMS cannot produce cleanly." },
    ],
    problemsWeSolve: [
      { problem: "Your commercial model doesn't fit the LMS's product model.", solution: "Bundles, seat purchases, memberships, and cohort rules built into the platform rather than glued together with coupons, plugins, and manual admin work." },
      { problem: "Enrolment reconciliation runs on a spreadsheet.", solution: "Payment providers, identity, and course access wired together as a tested handoff, so a successful sale grants the right access without a human in the middle." },
      { problem: "Compliance and reporting evidence is assembled by hand.", solution: "Attempts, versions, expiry, and certificates recorded as structured data with role-scoped reports, so an audit or renewal is a query, not a scramble." },
      { problem: "Migration risk is blocking a platform change.", solution: "Users, cohorts, progress, and content migrated with a mapping plan, dry-run validation, and a documented rollback path before cutover." },
      { problem: "Integrations break when a partner or system changes.", solution: "SSO, SIS, LTI 1.3, payments, video, and CRM connections built with typed contracts, retries, and observability rather than one-off scripts." },
    ],
    whatWeBuild: [
      { heading: "Student Portal", body: "Learner accounts, catalogue, enrolment, progress, assessments, certificates, and account recovery. Designed for the exact learner journey (self-paced catalogue, mentor-reviewed cohort, or hybrid) rather than a generic 'my courses' tab." },
      { heading: "Admin Dashboard", body: "Course publishing, enrolments, roles, cohorts, refunds, and support tools that an operator can use without emailing an engineer. Includes an audit trail so mistakes can be safely reversed." },
      { heading: "Integrations", body: "SSO (SAML, OIDC), SIS, LTI 1.3, payment providers (Stripe, Adyen, PayPal), video (Mux, Vimeo, Cloudflare Stream), CRM, and email, implemented with error handling, retries, and clear logs when a partner API misbehaves." },
      { heading: "Reporting & Analytics", body: "Role-scoped reports built around real decisions: overdue training by team, cohort completion, revenue by programme, at-risk learners. xAPI-compatible event stream so records stay portable across future systems." },
    ],
    process: [
      { step: "Week 1: map the work", detail: "Discovery sessions, a walkthrough of your current learner journey and admin workflows, and a written scope with the risky decisions flagged." },
      { step: "Weeks 2 to 3: prove the risky paths", detail: "SSO, payment, migration, or reporting path prototyped end to end so vague requirements become tested code, not planning-document phrases." },
      { step: "Weekly builds: working software", detail: "Live-review environments every week with the real learner and admin flows. Feedback lands in the next slice, not after months of build." },
      { step: "Launch: cutover and handover", detail: "Import validation, role and permission acceptance tests, operational runbooks, and code plus infrastructure handed over with continued support available but not required." },
    ],
    included: ["Product discovery and written scope", "UX and interface design system", "Learner-facing application (student portal)", "Admin dashboard and operator tools", "Identity and SSO integration", "Payment and commerce integration", "SIS or LTI 1.3 integration (where scoped)", "Data migration plan, dry run, and cutover", "Reporting and analytics module", "Automated test suite and CI pipeline", "Deployment infrastructure and runbooks", "Full source code and technical documentation", "Handover training for your operations team"],
    costBand: "The cost of a custom LMS moves with the same handful of decisions every time: how many distinct learner and admin flows, the shape of the data you're migrating, the integrations you can't avoid (payments, SSO, LTI), and how far reporting has to go beyond dashboards to actual evidence. We would rather scope a smaller first release with a clear second step than pretend every possible feature belongs in version one. Once the plan is specific, so is the number, shared with the assumptions and what would change it.",
    outcomes: "The result is a platform your team can explain without apologising for its limits. Learners see a coherent product. Administrators spend less time stitching systems together. And when a new revenue model or teaching idea arrives, you have a codebase that can change with it.",
    faqs: customLmsFaqs,
    stat: {
      value: "SCORM 1.2",
      label: "the content-packaging standard most existing courseware still ships in. A custom LMS has to import, launch, and report against it correctly on day one, or a whole library of learning material becomes stranded.",
      source: "ADL / SCORM",
      sourceUrl: "https://adlnet.gov/projects/scorm/",
    },
    relatedAlternativeSlugs: ["moodle"],
    relatedPostSlugs: ["how-much-does-a-custom-lms-cost-in-2026", "build-vs-buy-an-lms-the-honest-math", "hidden-cost-of-revenue-share-course-platforms", "custom-lms-vs-off-the-shelf-total-cost-of-ownership-over-three-years", "what-actually-drives-the-price-of-an-e-learning-build"],
    keywords: ["custom LMS development", "custom learning management system", "LMS development agency"],
  },
  {
    slug: "corporate-training-platform",
    title: "Corporate Training Platform Development",
    metaTitle: "Corporate Training Platform Development | Rizon",
    metaDescription: "Corporate training platform development for L&D teams that need training tied to their own roles, SSO, compliance evidence, reporting, and employee systems.",
    h1: "Corporate training platform development that works with the company you actually run.",
    heroSub: "For L&D and HR leads who need training records, role-based access, and reporting connected to their organisation, we build the platform around the work.",
    targetKeyword: "corporate training platform development",
    whoWeWorkWith: [
      { audience: "L&D leaders at mid-market and enterprise organisations", description: "Teams responsible for training completion, role clearance, and manager visibility across employees, contractors, and partners. The platform has to fit the organisation chart, not the other way around." },
      { audience: "Regulated industries", description: "Financial services, healthcare, safety, and energy organisations where a missing training record is a compliance failure and evidence has to survive an external audit, not just look good in a dashboard." },
      { audience: "Multi-tenant partner training operators", description: "Companies training external distributors, franchisees, or partners under separate branding, permissions, and reporting boundaries inside one operational platform." },
      { audience: "Companies with mixed workforces", description: "Employees on SSO, contractors on invite links, partners in isolated tenants. One platform, one identity model, and correct access on day one." },
    ],
    problemsWeSolve: [
      { problem: "SSO covers employees but not contractors, partners, or seasonal staff.", solution: "Hybrid identity: SAML or OIDC for employees, invited access for contractors, tenant-scoped SSO for partners, all mapped to the same role and access model." },
      { problem: "HRIS changes don't reach the LMS cleanly.", solution: "Scheduled or event-driven HRIS sync (Workday, BambooHR, Rippling, HiBob, custom) with role, department, and manager relationships propagated automatically." },
      { problem: "Compliance evidence is rebuilt from exports each quarter.", solution: "Structured evidence: attempts, acknowledgement, expiry, certificates, and material version, queryable and exportable per person, per role, per period." },
      { problem: "Audits require records that no single system owns.", solution: "Immutable audit log spanning training assignments, completions, admin actions, and role changes, with the reporting queries pre-built rather than assembled under pressure." },
      { problem: "Manager reporting either shows too much or too little.", solution: "Role-scoped dashboards: a line manager sees their team; a regional lead sees their region; nobody sees another client's records. Permissions enforced in the data layer, not just the UI." },
      { problem: "Partner training needs isolated branding, admin, and reporting.", solution: "Multi-tenant partner portals with separate identity, theming, and reporting boundaries, so each partner runs their own space inside one operational platform." },
    ],
    whatWeBuild: [
      { heading: "SSO", body: "SAML 2.0 and OIDC integration with Okta, Azure AD / Entra ID, Google Workspace, Ping, and custom IdPs. Just-in-time provisioning, group-to-role mapping, and clean deprovisioning when someone leaves." },
      { heading: "HRIS", body: "Workday, BambooHR, Rippling, HiBob, and custom HRIS integrations for people, roles, departments, and manager relationships. Change events flow to training assignments and access rules automatically." },
      { heading: "Compliance", body: "Assignment rules by role, region, and start date; renewal windows; grace periods; auto-escalation; and material versioning, so a policy change is a controlled rollout with an audit trail rather than an email chain." },
      { heading: "Audit", body: "Immutable, exportable audit log covering training assignments, completions, admin actions, role changes, and evidence access. Pre-built queries for the questions auditors actually ask." },
      { heading: "Reporting", body: "Role-scoped dashboards and scheduled reports for line managers, regional leads, L&D, and compliance. Answers management questions instead of dumping data into a shared drive." },
      { heading: "Role management", body: "Fine-grained roles and permissions modelled on your organisation: employees, managers, contractors, partners, and administrators, with permissions enforced at the API and data layer, not just the UI." },
      { heading: "Partner portals", body: "Multi-tenant workspaces with separate identity, branding, admin, and reporting boundaries. Each partner runs their own space; you keep operational visibility across all of them." },
    ],
    process: [
      { step: "Week 1: find the evidence trail", detail: "Trace one training requirement from policy to manager report. The handoffs where people email, export, or manually confirm reveal what the first release must solve." },
      { step: "Weeks 2 to 3: connect identity early", detail: "SSO, HRIS, and role modelling proved before the interface gets polished. A beautiful dashboard with the wrong access model is expensive wallpaper." },
      { step: "Weekly builds: real teams, real roles", detail: "Pilot with a real department using realistic role changes and completion states. Feedback from actual managers rather than a staged demo." },
      { step: "Launch: cutover and handover", detail: "Access acceptance tests, audit-report validation, operational runbooks, and code plus infrastructure handed over with continued support available on your terms." },
    ],
    included: ["Product discovery and access-model design", "Role and permission modelling", "SSO integration (SAML / OIDC)", "HRIS integration and sync", "Training assignment and completion engine", "Compliance rules and material versioning", "Audit log and exportable evidence store", "Role-scoped reporting and dashboards", "Multi-tenant partner portals (where scoped)", "Automated test suite and CI pipeline", "Deployment infrastructure and runbooks", "Full source code and technical documentation", "Handover training for L&D and operations"],
    costBand: "Corporate training work moves on a small set of decisions: the identity model (SSO, roles, contractors, partners), which HR system is the source of truth, what compliance evidence has to survive an audit, whether partner or multi-tenant training is in scope, and how much historic record migration is required. We scope the reporting questions before estimating, because reporting is where vague requirements become expensive. Once the plan is specific we quote against it and show the assumptions.",
    builtOn: {
      text: "Under the hood, this is custom LMS development shaped around your organisation, with LTI development for the content tools and third-party courses your teams already license.",
      links: [{ text: "custom LMS development", href: "/services/custom-lms-development" }, { text: "LTI development", href: "/services/lti-development" }],
    },
    outcomes: "Managers get an answer they can act on. Learners receive the training that applies to them. The L&D team stops spending the last afternoon of the month turning exports into evidence.",
    faqs: corporateFaqs,
    stat: {
      value: "xAPI",
      label: "the open Experience API standard. It lets a training record follow a learner across systems into a store you own, instead of dying inside one vendor's LMS. That portability is the whole point of building rather than renting.",
      source: "xAPI Spec (ADL)",
      sourceUrl: "https://github.com/adlnet/xAPI-Spec",
    },
    relatedAlternativeSlugs: ["docebo", "talentlms"],
    relatedPostSlugs: ["sso-options-for-learning-platforms", "student-data-security-checklist-for-edtech-teams", "custom-lms-vs-off-the-shelf-total-cost-of-ownership-over-three-years"],
    keywords: ["corporate training platform development", "custom corporate LMS", "L&D platform development"],
  },
  {
    slug: "course-platform-for-creators",
    title: "Custom Course Platform for Creators",
    metaTitle: "Custom Course Platform for Creators | Rizon",
    metaDescription: "A custom course platform for creators who have outgrown template course software and need full control of payments, learner experience, branding, and product roadmap.",
    h1: "A custom course platform for creators who have outgrown the template.",
    heroSub: "For established course creators who need their checkout, member experience, and learning flow to match the business they have built, we make the platform yours.",
    targetKeyword: "custom course platform",
    whoWeWorkWith: [
      { audience: "Established course creators", description: "Founders with a proven offer and repeat customers whose current hosted platform has become the reason support keeps explaining exceptions to buyers." },
      { audience: "Cohort programme operators", description: "Programmes with defined start dates, mentor reviews, and staged access where the tool has to enforce the sequence rather than fight it." },
      { audience: "Membership and community operators", description: "Subscription or membership offers with tiered access, drip content, and renewal logic that a generic membership plugin cannot express cleanly." },
      { audience: "Agencies and coaches with proprietary frameworks", description: "Practitioners whose framework is the product: applications, assessment, delivery, and follow-on offers connected in one owned system." },
    ],
    problemsWeSolve: [
      { problem: "The checkout can't represent how you actually sell.", solution: "Custom purchase flows for bundles, memberships, applications, staged payment plans, and team seats, tied directly to access rules and the payment provider you already use." },
      { problem: "Team and B2B purchases become a manual imports queue.", solution: "Company purchase, seat allocation, invited-learner onboarding, and consolidated invoicing built as first-class flows rather than a coupon plus a spreadsheet." },
      { problem: "The platform takes a revenue share you can't renegotiate.", solution: "Owned checkout that connects directly to Stripe (or your provider) with no platform fee on top, and reporting that gives you the picture your hosted dashboard hides." },
      { problem: "Migration from Teachable, Thinkific, or Kajabi is stalled by risk.", solution: "A mapped migration of courses, students, purchases, and access rules with a dry run, a receipts-and-access acceptance test, and a documented rollback." },
      { problem: "Learner support keeps bridging gaps the software should handle.", solution: "Admin tools that let your team grant access, refund, resend receipts, and correct enrolments in two clicks instead of five separate tools." },
    ],
    whatWeBuild: [
      { heading: "Custom Checkout", body: "Purchase and access rules built around what you sell: individual courses, cohorts, memberships, bundles, team seats, applications, and staged payment plans. Connected to Stripe, Adyen, or PayPal with the successful-payment path tested end to end." },
      { heading: "Student Dashboard", body: "Learner account, purchases, progress, lessons, community access, and support entry point designed around your programme rather than a template course grid. Membership and drip logic enforced in the product, not bolted on." },
      { heading: "Admin Dashboard", body: "Operational tools your team uses every launch week: grant access, move learners between cohorts, resend emails, refund a purchase, and investigate a failed checkout without opening five separate tools." },
      { heading: "Reporting & Analytics", body: "Revenue, retention, refund patterns, engagement, and support signals in one view. Answers concrete questions: which offer converts but never starts, which module drives refunds, which cohort renews." },
    ],
    process: [
      { step: "Week 1: map one real offer", detail: "Discovery around your best-selling offer, its awkward exception cases, and the checkout-to-first-lesson flow that decides whether the product feels organised." },
      { step: "Weeks 2 to 3: prove the risky paths", detail: "Payment, migration, and access rules prototyped and tested before design polish. Vague requirements become code with acceptance tests." },
      { step: "Weekly builds: working software", detail: "Live-review environments every week showing purchase, enrolment, and learning actions working together. Assumptions get challenged before they harden." },
      { step: "Launch: cutover and handover", detail: "Migration validation, launch-week runbook, and code plus infrastructure handed over. Continued support available; never required." },
    ],
    included: ["Product discovery and written scope", "UX and interface design system", "Custom checkout and account flows", "Course, cohort, and membership experience", "Admin operations dashboard", "Payment provider integration", "Email and lifecycle automation integration", "Migration plan, dry run, and cutover", "Reporting and analytics module", "Automated test suite and CI pipeline", "Deployment infrastructure and runbooks", "Full source code and technical documentation", "Launch-week support and handover training"],
    costBand: "The cost of a creator platform follows the shape of the offer. Custom checkout logic, memberships, team purchasing, a migration from an existing catalogue, and a built-in community are the usual drivers, along with how much of the buyer-to-learner handoff has to feel bespoke. We protect the first release by choosing the offer that makes money now, not the hypothetical offer three years away, and quote against that specific plan with the assumptions in the open.",
    builtOn: {
      text: "The platform itself is custom LMS development built around your offer. If you sell through WooCommerce and deliver in Moodle today, a WooCommerce to Moodle integration can connect the two while you decide whether to move.",
      links: [{ text: "custom LMS development", href: "/services/custom-lms-development" }, { text: "WooCommerce to Moodle integration", href: "/services/woocommerce-to-moodle" }],
    },
    outcomes: "You control the commercial rules, the member experience, and the pace of product changes. More importantly, your support team stops being asked to manually bridge gaps the software should handle.",
    faqs: creatorFaqs,
    stat: {
      value: "2.9% + 30¢",
      label: "Stripe's standard US online card fee. That is the real cost of owning your checkout. A revenue-share platform takes a slice of every sale on top of processing like this, which is why the maths turns once your volume is real.",
      source: "Stripe",
      sourceUrl: "https://stripe.com/pricing",
    },
    relatedAlternativeSlugs: ["teachable", "thinkific", "kajabi"],
    relatedPostSlugs: ["hidden-cost-of-revenue-share-course-platforms", "leaving-teachable-a-migration-checklist"],
    keywords: ["custom course platform", "Teachable alternative for creators", "creator platform development"],
  },
  {
    slug: "school-student-portal-development",
    title: "School & Student Portal Development",
    metaTitle: "School Student Portal Development | Rizon",
    metaDescription: "School student portal development for institutions that need one tailored place for students, parents, teachers, learning, grades, data, and essential services.",
    h1: "School student portal development for an institution that wants one front door.",
    heroSub: "For school and university IT leaders whose learners, parents, teachers, and staff keep crossing between disconnected systems, we build the portal around the institution.",
    targetKeyword: "school portal development",
    whoWeWorkWith: [
      { audience: "K-12 schools and multi-school districts", description: "Institutions needing one front door for students, parents, and teachers, where the SIS, LMS, and communication tools currently live in separate logins." },
      { audience: "Higher-ed institutions and universities", description: "Colleges with LMS, SIS, registration, and finance in disconnected products, and a growing need for one portal experience per role." },
      { audience: "Independent and private schools", description: "Schools with specific pedagogical models and communication expectations that a generic vendor portal cannot accommodate without compromises." },
      { audience: "International schools and networks", description: "Multi-campus institutions that need consistent access, permissions, and reporting across sites while respecting local variations in curriculum and language." },
    ],
    problemsWeSolve: [
      { problem: "Students, parents, and teachers manage five logins for one school.", solution: "One portal that unifies sign-in, timetable, assignments, grades, messages, and administrative tasks across the systems your institution already runs." },
      { problem: "SIS is the source of truth but nothing else knows.", solution: "SIS integration (PowerSchool, Infinite Campus, SchoolLogic, Ellucian, and custom) with enrolment, class membership, and guardian relationships propagated to the portal automatically." },
      { problem: "Parent access is a compliance problem waiting to happen.", solution: "Guardian relationships modelled as first-class access rules: correct child visibility, sibling grouping, custody-aware permissions, and an audit log of every view." },
      { problem: "Gradebook lives in one product; the LMS lives in another.", solution: "Teacher-facing gradebook integrated with the LMS and SIS, so an assessment moves cleanly from submission to grade to student record without a manual export." },
      { problem: "Legacy accounts, roles, and course data are blocking a move.", solution: "Staged migration with SIS as the source of truth, dry-run validation, and a rollback plan so the switch happens without losing a term's worth of records." },
      { problem: "Every new tool means another security review.", solution: "Portal designed for student-data compliance (FERPA, GDPR where applicable) with access rules, retention, and audit built into the data model rather than added at the end." },
    ],
    whatWeBuild: [
      { heading: "SIS Integration", body: "PowerSchool, Infinite Campus, Ellucian, SchoolLogic, and custom SIS integration for enrolment, class membership, timetables, and guardian relationships. Sync validated before every rollout so a bad import does not reach production." },
      { heading: "Parent Portal", body: "Guardian-scoped views of children (including siblings and split-custody cases), messages, attendance, grades, and school communications, with an access log administrators can inspect when needed." },
      { heading: "Teacher Dashboard", body: "Class rosters, attendance, assignment submission and feedback, gradebook, and communication tools that respect class-level permissions instead of showing every teacher every student." },
      { heading: "Student Dashboard", body: "Timetable, assignments, submissions, grades, messages, and resources in one place, with role-appropriate visibility and a clear next action rather than an institutional sitemap." },
      { heading: "SSO", body: "SAML and OIDC integration with Google Workspace for Education, Microsoft Entra ID, Clever, ClassLink, and custom IdPs. OneRoster rostering supported where the SIS provides it." },
      { heading: "Permissions", body: "Role, class, cohort, and guardian-relationship permissions modelled in the data layer. Access decisions are enforced by the API, not just hidden in the UI, so a direct request cannot bypass what a screen hides." },
      { heading: "Reporting", body: "Role-scoped reporting for teachers, department heads, administrators, and district leaders, with scheduled exports and pre-built queries for the questions inspection and accreditation actually ask." },
    ],
    process: [
      { step: "Week 1: walk a real school day", detail: "Trace a student, guardian, teacher, and admin task through current systems. Handoffs reveal what the portal must unify and what it should leave alone." },
      { step: "Weeks 2 to 3: set the source of truth", detail: "Which system owns identity, enrolment, grades, and learning data. Unglamorous but essential: prevents the portal from creating a second, unreliable version of school records." },
      { step: "Weekly builds: pilot with real roles", detail: "A small group of students, teachers, and parents test the priority flows. Their confusion is useful, and far cheaper than a full-term rollout followed by a support backlog." },
      { step: "Launch: governance and cutover", detail: "Documented access, support, and change-approval paths. Data migration validated, staff runbooks written, and code plus infrastructure handed over with continued support available." },
    ],
    included: ["Product discovery and access-model design", "Role, class, and guardian permission modelling", "SIS integration (PowerSchool, Infinite Campus, Ellucian, custom)", "SSO integration (SAML, OIDC, OneRoster where available)", "Parent, teacher, student, and admin portals", "Gradebook and assignment integration", "Messaging and school-communication flows", "Migration plan for legacy accounts and course data", "Role-scoped reporting and scheduled exports", "Security review aligned with student-data expectations", "Automated test suite and CI pipeline", "Deployment infrastructure and runbooks", "Full source code and technical documentation", "Governance and operations handover"],
    costBand: "The cost of a school portal changes sharply with SIS integration, the number of roles the portal serves, parent access, gradebook requirements, legacy data migration, and whether the portal also replaces an LMS or sits alongside it. We recommend beginning with the student service that causes the most friction, then expanding from a stable base, and quoting against that specific first release rather than a generic range.",
    builtOn: {
      text: "The portal is built with custom LMS development or extends the Moodle you already run through Moodle development, and ties sign-in together using the approaches in SSO options for learning platforms.",
      links: [{ text: "custom LMS development", href: "/services/custom-lms-development" }, { text: "Moodle development", href: "/services/moodle-development" }, { text: "SSO options for learning platforms", href: "/blog/sso-options-for-learning-platforms" }],
    },
    outcomes: "Students get a clearer path through school life. Teachers and staff spend less time translating between systems. The institution gains a portal it can shape around its own policies instead of asking every department to adapt to a generic product.",
    faqs: schoolFaqs,
    stat: {
      value: "FERPA",
      label: "the U.S. law governing who may see a student's education records. A portal has to enforce that in its permission model, by design, not by asking staff to remember a policy. Get the guardian-relationship rules wrong and you have a compliance problem, not a bug.",
      source: "U.S. Dept. of Education",
      sourceUrl: "https://studentprivacy.ed.gov/faq/what-ferpa",
    },
    relatedAlternativeSlugs: ["moodle"],
    relatedPostSlugs: ["canvas-breach-student-data-security", "migrating-from-lti-1-1-to-lti-1-3-a-practical-guide-for-tool-builders"],
    keywords: ["school portal development", "student portal development", "custom school LMS"],
  },
];

export function getServiceBySlug(slug: string): ServicePage | undefined {
  return services.find((service) => service.slug === slug);
}
